//! Python-compatible decimal rounding.
//!
//! This module exists because of one line in `clearing_cpm`:
//!
//! ```python
//! price = round(price, 6)
//! ```
//!
//! CPython's `round(x, n)` rounds the *exact decimal value* of the double,
//! breaking ties to even. The obvious Rust translation does neither of those
//! things:
//!
//! ```text
//! (x * 1e6).round() / 1e6
//! ```
//!
//! `f64::round` breaks ties away from zero, and the `* 1e6` introduces its own
//! rounding error before the tie is even evaluated, so the two disagree on
//! inputs that are nowhere near a halfway case.
//!
/// Round `x` to `ndigits` decimal places with CPython's `round()` semantics.
///
/// Non-finite inputs are returned unchanged rather than formatted, since
/// `format!("{:.6}", f64::INFINITY)` yields `"inf"`, which does not round-trip.
pub fn py_round(x: f64, ndigits: usize) -> f64 {
    if !x.is_finite() {
        return x;
    }
    // `{:.*}` is exact and ties-to-even, matching _Py_dg_dtoa mode 3.
    format!("{:.*}", ndigits, x)
        .parse::<f64>()
        .unwrap_or(x)
}

#[cfg(test)]
mod tests {
    use super::py_round;

    /// The naive translation, kept only so the tests can demonstrate that it is
    /// wrong.
    fn naive_round(x: f64, ndigits: i32) -> f64 {
        let f = 10f64.powi(ndigits);
        (x * f).round() / f
    }

    #[test]
    fn matches_cpython_on_known_values() {
        // (input, expected) pairs generated by CPython 3.12 round(x, 6).
        // See tools/gen_round_cases.py for how to regenerate.
        let cases: &[(f64, f64)] = &[
            (1.2973499, 1.29735),
            (0.0000005, 0.0),
            (0.0000015, 0.000002),     
            (2.6755, 2.6755),
            (4.0100000000000005, 4.01),
            (0.1 + 0.2, 0.3),
            (1e-9, 0.0),
            (12.3456785, 12.345678),  
            (-1.2973499, -1.29735),
        ];
        for &(input, expected) in cases {
            let got = py_round(input, 6);
            assert_eq!(
                got, expected,
                "py_round({input:?}, 6) = {got:?}, expected {expected:?}"
            );
        }
    }

    #[test]
    fn naive_translation_diverges() {
        assert_eq!(py_round(0.0000005, 6), 0.0);
        assert_ne!(naive_round(0.0000005, 6), 0.0);
    }

    #[test]
    fn non_finite_passes_through() {
        assert!(py_round(f64::NAN, 6).is_nan());
        assert_eq!(py_round(f64::INFINITY, 6), f64::INFINITY);
    }

    #[test]
    fn idempotent() {
        for &x in &[1.29735_f64, 0.000002, 4.01, 6.0] {
            assert_eq!(py_round(py_round(x, 6), 6), py_round(x, 6));
        }
    }
}
